; PlatformIO Project Configuration File
;
; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

; Library dependencies
lib_deps = 
    ; NimBLE core library for memory-efficient BLE
    h2zero/NimBLE-Arduino @ ^1.4.0
    ; Wrapper for creating composite HID Keyboard & Mouse
    https://github.com/A-box1000/ESP32-NimBLE-Combo.git

; Serial Monitor settings (matching Serial.begin in main.cpp)
monitor_speed = 115200
monitor_filters = time, colorize

; Board specific build flags for XIAO ESP32-S3
build_flags = 
    ; Disable default USB mode
    -D ARDUINO_USB_MODE=0
    ; Enable USB CDC on boot to see Serial prints via USB-C
    -D ARDUINO_USB_CDC_ON_BOOT=1